#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'rbenv', :git => "git://github.com/fnichol/chef-rbenv"
cookbook 'chef-instant-coder', :git => "git://github.com/socalvin/chef-instant-coder"
